theme = "nord-dark"

icons = "awesome6"

[[block]]
block = "music"
format = "{combo}"
buttons = ["prev", "play", "next"]
player = "spotify"
marquee_speed = 0.25
marquee_interval = 5
dynamic_width = true

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
