[theme]
theme = "nord-dark"

[theme.overrides]
#info_bg = "#66390C"
#idle_bg = "#525252"
#warning_bg = "#E6D965"
#good_bg = "#BD7EB8"
#critical_bg = "#FF0000"
#alternating_tint_bg = "#40235E"

[icons]
icons = "awesome6"


[[block]]
block = "music"
format = "$combo.str(20) $prev $play $next|"
player = "spotify"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "battery"

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
