[theme]
theme = "nord-dark"

[icons]
icons = "awesome6"

[[block]]
block = "music"
format = "$icon $combo $prev $play $next |"
player = "spotify"

[[block]]
block = "sound"

[[block]]
block = "cpu"
interval = 1
 
[[block]]
block = "time"
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d-%m-%Y %R') "

